version: '2.4'
networks:
  cassandra:

services:
  cass1:
    image: cassandra:3.11.8
    container_name: cass1
    hostname: cass1
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
      interval: 5s
      timeout: 5s
      retries: 60
    networks:
      - cassandra
    ports:
      - "9042:9042"
    volumes:
      - .\data\cass1:/var/lib/cassandra
      - .\etc\cass1:/etc/cassandra
    environment: &environment
      CASSANDRA_SEEDS: "cass1,cass2"
      CASSANDRA_CLUSTER_NAME: Sparkify
      CASSANDRA_DC: DC1
      CASSANDRA_RACK: RAC1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_NUM_TOKENS: 128

  cass2:
    image: cassandra:3.11.8
    container_name: cass2
    hostname: cass2
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
      interval: 5s
      timeout: 5s
      retries: 60
    networks:
      - cassandra
    ports:
      - "9043:9042"
    volumes:
      - .\data\cass2:/var/lib/cassandra
      - .\etc\cass2:/etc/cassandra
    environment: *environment
    depends_on:
      cass1:
        condition: service_healthy

  cass3:
    image: cassandra:3.11.8
    container_name: cass3
    hostname: cass3
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 5s
      timeout: 5s
      retries: 60
    networks:
      - cassandra
    ports:
      - "9044:9042"
    volumes:
      - .\data\cass3:/var/lib/cassandra
      - .\etc\cass3:/etc/cassandra
    environment: *environment
    depends_on:
      cass2:
        condition: service_healthy